SD_Magnet_timeStamp: sapi_examples/edu-ciaa-nxp/sapi_sd_magnet_timeStamp/src/sd_spi.c File Reference
sd_spi.c File Reference
#include "sd_spi.h"
#include "sapi.h"
#include <math.h>
#include "ff.h"
Macros
#define FILENAME "DATOS.TXT"
#define BAUD_RATE 115200
Functions
char * itoa (int value, char *result, int base)
void showDateAndTime (rtc_t *rtc)
void sendHmc5883lToUart (int16_t axis, uint8_t axisName)
bool_t diskTickHook (void *ptr)
int main (void)
Variables
rtc_t rtc
UINT nbytes
Macro Definition Documentation
BAUD_RATE
#define BAUD_RATE 115200
Definition at line 48 of file sd_spi.c.
Referenced by main().
FILENAME
#define FILENAME "DATOS.TXT"
Definition at line 47 of file sd_spi.c.
Function Documentation
diskTickHook()
bool_t diskTickHook (void * ptr)
Definition at line 289 of file sd_spi.c.
References disk_timerproc().
Referenced by main().
itoa()
char * itoa (int value, char * result, int base)
C++ version 0.4 char* style "itoa": Written by Luk?s Chmela Released under GPLv3.
Definition at line 218 of file sd_spi.c.
Referenced by sendHmc5883lToUart(), and showDateAndTime().
main()
int main (void)
Definition at line 119 of file sd_spi.c.
References BAUD_RATE, diskTickHook(), and rtc.
sendHmc5883lToUart()
void sendHmc5883lToUart (int16_t axis, uint8_t axisName)
Definition at line 79 of file sd_spi.c.
References itoa().
showDateAndTime()
void showDateAndTime (rtc_t * rtc)
Definition at line 242 of file sd_spi.c.
References itoa().
Variable Documentation
nbytes
UINT nbytes
Definition at line 63 of file sd_spi.c.
rtc
rtc_t rtc
Definition at line 62 of file sd_spi.c.
Referenced by main().